@startmindmap
* Settings
** General Settings
*** Time
**** Summer Time
**** UTC Zone
*** Language
** Session Overview
*** Sessions 
**** Session Laps
**** Delete Session
*** Delete All Session
** Track Management
*** Tracks
**** Delete Track
*** Delete All Tracks
** Bluetooth Settings
*** Enable/Disable Bluetooth
*** Pair Device
*** Paired Devices
** Wi-Fi Settings
*** Enable/Disable Wi-Fi
*** Connection Information
@endmindmap