name: "linux-install-qt"
description: "Install Qt for Linux in a specific version"
inputs:
  os:
    description: 'Runner OS'
    required: false
    default: 'default'
runs:
  using: "composite"
  steps:
    - name: "Install Qt for Linux"
      if: (inputs.os == 'ubuntu-latest') || (inputs.os == 'ubuntu-24.04') || (inputs.os == 'ubuntu-22.04') || (inputs.os == 'default')
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.5.*'
        cache: 'true'
        modules: 'qtlocation qtpositioning'
        setup-python: false
